### PR TITLE
Made GKImageCropViewController use the iOS7 style when running on iOS7 o...

### PR DESCRIPTION
**Pull request by Cheblon**
GKImageCropViewController will switch to use an iOS7 style picker on devices running iOS7 or later.

### CODE REVIEW

**Comment by hakanw** [comment]
Please merge this if it fixes iOS 7 style. It really looks awful right now on iOS 7.

**Comment by gekitz** [comment]
@Cheblon can we do something about the indentation?

**Comment by Cheblon** [comment]
@gekitz hopefully that sorted it, had a few tabs in there for some reason. I made this iOS7 change quickly for my own app and thought it would be useful. It works for me but I'm new to github so I've probably done something stupid somewhere!

**Comment by hakanw** [comment]
Are all the remaining issues with the PL fixed now for merge?

**Comment by Cheblon** [comment]
All looks good from my end.

**Pull request merged**
